### ISSUE TITLE
about OpenCV3

### ISSUE THREAD

**Issue by hoolang** [JoeHowse/iOSWithOpenCV#1]
Hello, your book name **iOS Application Development with OpenCV 3**, but I found you used OpenCV 2 in your projects. Do you have any demo with  OpenCV 3 ?

**Comment by JoeHowse** [comment]
The book and projects use OpenCV 3. Even in OpenCV 3, the name "opencv2" still appears in the framework file and header path. Maybe this is the cause of your confusion.
