### ISSUE TITLE
opencv2.framework does not work...!

### ISSUE THREAD

**Issue by areslui** [JoeHowse/iOSWithOpenCV#5]
Followed the instruction and download the framework but it does not work. None any headers in this file.
<img width="1179" alt="screen shot 2017-05-10 at 1 54 42 pm" src="https://cloud.githubusercontent.com/assets/12028247/25884954/57dfee92-3588-11e7-89ee-3d2c3b6ea114.png">

this one is working fine, but it is opencv2 version and does not has SFM module inside.
<img width="1050" alt="screen shot 2017-05-10 at 1 54 11 pm" src="https://cloud.githubusercontent.com/assets/12028247/25885013/9a1cbcc2-3588-11e7-96d3-62bab181b8d6.png">
 
Could you please tell me what am I doing wrong?
Thanks

**Comment by JoeHowse** [comment]
Hi, @areslui.  My opencv2.framework build from this repository does contain headers, and so does the latest opencv2.framework file (currently, version 3.2.0) from http://opencv.org/releases.html.

The version really is OpenCV 3.  The name "opencv2" in the filename and headers doesn't refer to the OpenCV version number.  It just means that this is the new C++ API and not the old C API.

See https://github.com/JoeHowse/iOSWithOpenCV/releases for notes about the version number and modules of my opencv2.framework build.  This build should contain everything you need for the projects in this repository.  It seems that you have a different project that may require a different version and different modules, so you will need to make your own custom build of opencv2.framework.

**Comment by theoknock** [comment]
I can verify that the version Joe uses is 3.x; but, like you, I could not install OpenCV in my own projects any other way but with CocoaPods; and, only then, after opening the project in the workspace file created by CocoaPods AND after appending an extra "m" to each implementation file using an OpenCV function.

**Comment by theoknock** [comment]
By the way, the #include headers will be different as well.

**Comment by areslui** [comment]
Thank you for your explanation.
