### ISSUE TITLE
Building the framework from source with extra modules

### ISSUE THREAD

**Issue by ghost** [JoeHowse/iOSWithOpenCV#6]
**Hi,
I have this problem:**
![screen shot 2017-06-05 at 4 31 41 pm](https://cloud.githubusercontent.com/assets/22445295/26785706/7c964144-4a0c-11e7-93fc-5b37b947f99e.png)
**Inside of OpenCV3 folder I have:**
![screen shot 2017-06-05 at 4 27 14 pm](https://cloud.githubusercontent.com/assets/22445295/26785653/2fe6b5cc-4a0c-11e7-9527-b0d1cc91c9c3.png)

**In terminal I put:**
_sudo[and without sudo] ./OpenCV3/opencv/platforms/ios/build_framework.py /Users/ronysteel/Developer/iOS/Other/OpenCV3/framework --contrib /Users/ronysteel/Developer/iOS/Other/OpenCV3/opencv_contrib_

the error appear:
_sudo: ./OpenCV3/opencv/platforms/ios/build_framework.py: command not found_

Can you help me to run successful and build that opencv custom framework from your book?

Thank you

**Comment by theoknock** [comment]
You are wasting your time in asking this question, and Joe would be wasting his time answering it.

Use CocoaPods to install OpenCV 3. Plain and simple.

James
408-685-4049
________________________________

**Comment by JoeHowse** [comment]
Hi @ronysteel.  @theoknock and some others have had success with CocoaPods, but personally I'm continuing to use the approach outlined in the book.

First, please confirm that `OpenCV3/opencv/platforms/ios/build_framework.py` exists. Assuming it does exist, there may be a file permissions issue. Make the file executable by running:

```
$ chmod +x OpenCV3/opencv/platforms/ios/build_framework.py
```

Then try to execute it again.  If this still doesn't work, try to run it with the Python interpreter:

```
$ python OpenCV3/opencv/platforms/ios/build_framework.py
```

Let me know how it works.  Thanks.

**Comment by theoknock** [comment]
Use CocoaPods. Joe: don't answer this question.

James
408-685-4049
________________________________

**Comment by ghost** [comment]
@JoeHowse Thank you, it works!
@theoknock Thank you too, Man, respect!

**Comment by ghost** [comment]
@JoeHowse Thank you and for your amazing book!

**Comment by ghost** [comment]
@JoeHowse  BTW, the size of Builded framework is 300MB+, is normally?

**Comment by JoeHowse** [comment]
Glad it worked.  Yes, the framework is normally big.  If you need to make it smaller, you can exclude some of the optional OpenCV modules and rebuild.

For the future reference of anyone reading this thread:  I don't personally have experience with CocoaPods but it's probably a great choice as a tool to manage pre-packaged builds of OpenCV, opencv_contrib, and lots of other libraries.  Particularly, this may suit your needs well if you're simply looking for a recent stable build.  On the other hand, manually building from source gives you complete flexibility in case you want to build from OpenCV's master branch, customize the choice of modules, patch the source code, etc.  Different approaches will suit different needs.

Thanks!

**Comment by ghost** [comment]
Thank you @JoeHowse 
Last question:
Do you have any information about document detection+Crop+Perspective+OCR+Change DPI?
Maybe you will prepare that in your next book?

Thank you

**Comment by JoeHowse** [comment]
[Mastering OpenCV 3](https://www.packtpub.com/application-development/mastering-opencv-3-second-edition) is a good C++ book that contains a chapter on license plate detection and recognition. This may be comparable to your document detection + OCR problem.

**Comment by ghost** [comment]
@JoeHowse Wow!!! That's amazing!!! Thank you!
