### ISSUE TITLE
Build framework with xfeatures2d and xphoto modules

### ISSUE THREAD

**Issue by ghost** [JoeHowse/iOSWithOpenCV#7]
Hi, 
Sorry please, but how to build framework with xfeatures2d and xphoto modules?

Best Regards

**Comment by JoeHowse** [comment]
They are part of `opencv_contrib`, so I think issue #6 covers this.

**Comment by ghost** [comment]
Hi, I bought this mastering-opencv book, but in is not indicated that question...

Best regards

PS: Good book!

**Comment by JoeHowse** [comment]
Mastering OpenCV 3 (specifically, Chapter 3 on license plate recognition) may help with your other query about learning OCR.

As for xfeatures2d and xphoto, they are part of opencv_contrib.  Based on the comments in issue #6, I believe you succeeded in building OpenCV with opencv_contrib, so you would already have xfeatures2d and xphoto as part of your framework.  The rest of the iOS Application Development with OpenCV 3 book contains some examples that use xfeatures2d (the BeanCounter project in Chapter 5) and xphoto (the CoolPig project in Chapter 1).  I hope this helps.

**Comment by ghost** [comment]
@JoeHowse  can you send me an e-mail test please?
I want to ask you something, please.

Best regards

**Comment by JoeHowse** [comment]
I don't have your email address but you can email me.  You'll find my email listed in the book or [on my support page](http://nummist.com/opencv/) for the books.
